# This is a basic workflow that is manually triggered

name: Build for NFS Host

on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npm run build --if-present
      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.3.0
        with:
          add: 'src/api/frontend'
          branch: nfs-build
          default_author: github_actions
          message: 'Update packaged react app'
          pull_strategy: 'NO-PULL'
          remove: 'src/webapp/ -r'
