# This is a basic workflow that is manually triggered

name: Build for NFS Host

on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: npm install 
        working-directory: ./src/webapp
        run: npm ci
      - name: npm build
        working-directory: ./src/webapp
        run: npm run build
#       - name: Add & Commit
#         uses: EndBug/add-and-commit@v7.3.0
#         with:
#           add: 'src/api/frontend'
#           branch: nfs-build
#           default_author: github_actions
#           message: 'Update packaged react app'
#           pull_strategy: 'NO-PULL'
#           remove: 'src/webapp/ -r'
      - name: Remove unwanted files
        run: rm -r src/webapp/
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3.10.1
        with:
         commit-message: "[bot] build for nfs, rm webapp src"
         branch: nfs-build-auto
         base: nfs-live
         title: Latest changes for nfs-live
         body: |
           Latest changes from main built for api host
           
           This should not be merged to `main`.
           This PR was created by automation.
         
        

