# This is a basic workflow that is manually triggered

name: Build for NFS Host

on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Remove react app from API static folder
        run: rm -r src/api/frontend/
      - name: npm install 
        working-directory: ./src/webapp
        run: npm ci
      - name: npm build (and copy to API static folder)
        working-directory: ./src/webapp
        run: npm run build
      - name: Commit to nfs-build-auto
        uses: EndBug/add-and-commit@v7.3.0
        with:
          add: 'src/api/frontend'
          branch: nfs-build-auto
          default_author: github_actions
          message: 'update react app in API static folder'
          pull_strategy: 'NO-PULL'
          remove: "['src/webapp/ -r', '.github']"
      - name: Open PR to nfs-live
        uses: repo-sync/pull-request@v2.6
        with:
           source_branch: nfs-build-auto
           destination_branch: nfs-live
           pr_title: "Latest changes from ${{ env.GITHUB_REF }} for nfs-live"
           pr_body: "Latest changes from `${{ env.GITHUB_REF }}` built `nfs-live`.\nThis is an automated PR from ${{ env.GITHUB_WORKFLOW }} run ${{ env.GITHUB_RUN_NUMBER }}"
           github_token: ${{ secrets.GITHUB_TOKEN }}


